name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Cache Docker layers to speed up builds
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Build and push Docker images
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./backend/Dockerfile
        push: false
        tags: user/app-backend:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    # Load updated cache
    - name: Load updated cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Run Docker Compose to start the services
    - name: Run Docker Compose
      run: docker-compose up -d

    # Optionally, you can add steps here to check the health of your application
    # For example, a simple curl request to the homepage or a health check endpoint

    # Stop and remove Docker containers
    - name: Cleanup
      run: docker-compose down
